server:
  port: 8282

spring:
  datasource:
    url: jdbc:mysql://114.55.254.24:3306/security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #    redis配置
  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 1
    # redis服务器地址（默认为loaclhost）
    host: 114.55.254.24
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: 112233
    # redis连接超时时间（单位毫秒）
    timeout: 1000
    # redis连接池配置

    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
  web:
    resources:
      static-locations: file:E:\\学习\\web前后端\\预学生约系统\\新建文件夹\\physical-fitness\\images
#      static-locations: file:/opt/reserveApp/images

